### ISSUE TITLE
吃相难看,搞收费,pid自动获取得到,不一定抢得到

### ISSUE THREAD

**Issue by THE2022** [reeveee/zhimiao#1]

**Comment by reeveee** [comment]
收费就是难看，您这是什么牛逼理论。您有本事您厉害，您胸怀天下，无私奉献，这都是您的事情。

别人靠知识劳动赚取一些报酬，关您这位高高在上的人什么事情呢？

您不喜欢您可以走，没人拦着您，没必要恶语咬人。
